# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # See: https://hub.docker.com/r/circleci/node/
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install